name: Run Pre-Commit Validation

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    name: HASS and Hassfest Validation
    runs-on: "ubuntu-latest"
    steps:
        - name: pre-commit
          uses: pre-commit/action@v3.0.0
